version: "3.9"

services:
  #Database
  app-db:
    image: postgres
    container_name: app-db
    environment:
      POSTGRES_DB: "app-db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_ROOT_PASSWORD: "password"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d app-db -U user"]
      interval: 2s
      timeout: 5s
      retries: 20
    ports:
      - "5432:5432"
    volumes:
      - app-db-volume:/var/lib/mysql

  # Client app
  client:
    container_name: mancala-client-container
    build:
      dockerfile: ./Dockerfile
      context: ./mancala-client
    image: abeldlp/mancala-client
    env_file:
      - ./mancala-api/.env.docker
    volumes:
      - ./mancala-client/:/app
    ports:
      - "3000:3000"
    depends_on:
      - mancala-api

  #Mancala API
  mancala-api:
    container_name: mancala-api-container
    build:
      dockerfile: ./Dockerfile
      context: ./mancala-api
    image: abeldlp/mancala-api
    env_file:
      - ./mancala-api/.env.docker
    volumes:
      - ./mancala-api/:/app
    expose:
      - "8000"
    depends_on:
      app-db:
        condition: service_healthy

  #Api gateway
  api-gateway:
    container_name: mancala-api-gateway-container
    build:
      dockerfile: ./Dockerfile
      context: ./api-gateway
    image: abeldlp/api-gateway
    env_file:
      - ./api-gateway/.env.docker
    volumes:
      - ./api-gateway/:/app
    ports:
      - "5000:5000"
    depends_on:
      - mancala-api

volumes:
  app-db-volume:
