on:
    push:
        branches:
            - main

name: MANCALA IMAGE BUILD

jobs:
    run_api_tests:
        name: Run Mancala API Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version-file: "mancala-api/go.mod"

            - name: Install Go dependencies
              run: cd mancala-api && go mod download

            - name: Mancala API Test
              run: cd mancala-api && go test -v ./...

    run_api_gateway_tests:
        name: Run API Gateway Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version-file: "api-gateway/go.mod"

            - name: Install Go dependencies
              run: cd api-gateway && go mod download

            - name: Mancala API Gateway Test
              run: cd api-gateway && go test -v ./...

    build_mancala_api_container_and_push_image:
        name: Mancala API Container
        runs-on: ubuntu-latest
        needs: run_api_tests
        steps:
            - uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: ./mancala-api
                  file: ./mancala-api/Dockerfile
                  push: true
                  tags: ghcr.io/${{ secrets.DOCKER_USERNAME }}/mancala-api:latest

    build_api_gateway_container_and_push_image:
        name: API Gateway Container
        runs-on: ubuntu-latest
        needs: run_api_gateway_tests
        steps:
            - uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: ./api-gateway
                  file: ./api-gateway/Dockerfile
                  push: true
                  tags: ghcr.io/${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
